version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 6.0.0
  - dependency-name: google-auth-library
    versions:
    - 7.0.3
    - 7.0.4
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.4
  - dependency-name: faker
    versions:
    - 5.5.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
